### ISSUE TITLE
Plugin should consume/evaluate "responseElements" object

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog-plugin-aws#1]
The plugin currently doesn't evaluate all of the CloudTrail message's fields which makes some use cases hard or impossible to implement.

For examples, see this mailing list thread: https://groups.google.com/d/msg/graylog2/_2QfrMiOiXs/N-GCwi5xA6cJ

**Comment by baldzern4** [comment]
Hi joschi,

I have created a fix and pull request for this.

**Comment by prestonr83** [comment]
How can I implement this fix?

**Comment by baldzern4** [comment]
@prestonr83 just include the fix from the (still open) pull request #6.

**Comment by joschi** [comment]
Closed by merging #6.
