### ISSUE TITLE
Travis shows "This is not an active repository"

### ISSUE THREAD

**Issue by gliptak** [Graylog2/graylog-plugin-aws#113]
https://travis-ci.org/Graylog2/graylog-plugin-aws

**Comment by deeshe** [comment]
We are not using travis for this repository.

**Comment by gliptak** [comment]
So there is no build configured for this repo?

**Comment by jalogisch** [comment]
sorry for not be more specific - yes currently that is not configured. But we will do this after your notice.

May we ask why you want to look at that?

**Comment by gliptak** [comment]
I was working a quick review to learn more about the project and seeing how it is built (and a green build) is part of that.
