### ISSUE TITLE
Check support for AWS US Gov East region

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog-plugin-aws#118]
It looks that the library version we are using does not have support for the US Gov East region.
It was added in https://github.com/aws/aws-sdk-java/commit/d617b31353d63a8291ff0be66727ce771ad4c812, referenced in https://github.com/aws/aws-sdk-java/blame/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java#L28 

We are still on an older version, so updating the client version to the latest should quickly fix the issue.

**Comment by danotorrey** [comment]
I am investigating this.
