### ISSUE TITLE
Add Aws S3 Logs

### ISSUE THREAD

**Issue by limbo127** [Graylog2/graylog-plugin-aws#15]
Hello, 
is it possible to add S3 logs to your plugins
Regards, 
Nicolas Prochazka

**Comment by skny5** [comment]
+1

**Comment by dannyz29** [comment]
+ 1, would save the workaround of pulling it from S3 with some script and pushing it into Graylog

**Comment by sherzberg** [comment]
I have started this PR: https://github.com/Graylog2/graylog-plugin-aws/pull/30

**Comment by nobodyrandom** [comment]
Hey just wondering, how is this this feature going? Is there any direct way to pull from S3 yet?

**Comment by sherzberg** [comment]
@nobodyrandom have you checked out my PR and the comments there?

In the mean time, I also just pulled out my PR to a new repo that I am using: https://github.com/sherzberg/graylog-plugin-s3

This requires a small setup with s3 event notifications, but I think I have it all documented on my readme.

**Comment by nobodyrandom** [comment]
@sherzberg Yep just got it configured on for CloudTrail S3 bucket. Thank you for your great work!

Is there anyway to use the SNS from CloudTrail directly?

**Comment by sherzberg** [comment]
@nobodyrandom this plugin now supports CloudTrail directy, no need to use my S3 plugin: https://github.com/graylog-labs/graylog-plugin-aws#cloudtrail-setup-and-configuration

**Comment by radykal-com** [comment]
Hi @sherzberg 
I don't know if the S3 input differs enough from the CloudTrail one to be a different input.
CloudTrail logs are notified through SNS and read from S3. The only difference between CloudTrail and other logs shipped to S3 are the format of the logged lines. Maybe a single Input type for S3 could manage CloudTrail or any other logs shipped to S3 (like ELB logs for example). We only need a way to use the correct codec (define through input config or auto-detect)

@bernd what approach should we follow? Would be nice to integrate more S3 logs like CloudTrail input does

**Comment by jseiser** [comment]
Has there been any progress on this?  Having to process our ELB logs outside of Graylog is a real pain.

**Comment by joschi** [comment]
@jseiser No, but your contributions are welcome!

**Comment by dennisoelkers** [comment]
As there is now at least a subset of the desired functionality in the plugin and the issue's scope was hijacked by other users, I am closing this for now. If there are further feature requests, please open a new, more precise issue.
