### ISSUE TITLE
AWS Plugin looses connection when using proxy

### ISSUE THREAD

**Issue by Arsimael** [Graylog2/graylog-plugin-aws#17]
Hi,

We try to read our data from AWS via proxy, it works fine first, but then we recieve loads of errors and AWS looses connection:

> 2016-09-20T12:54:16.613Z INFO  [AmazonHttpClient] Unable to execute HTTP request: Connect to sapcloudtrail.s3.amazonaws.com:443 [sapcloudtrail.s3.amazonaws.com/54.231.72.51] failed: connect timed out
> org.apache.http.conn.ConnectTimeoutException: Connect to sapcloudtrail.s3.amazonaws.com:443 [sapcloudtrail.s3.amazonaws.com/54.231.72.51] failed: connect timed out
>         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
>         at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.http.conn.$Proxy154.connect(Unknown Source) ~[?:?]
>         at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:858) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:701) [graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:453) [graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:415) [graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:364) [graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3964) [graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1259) [graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1134) [graylog-plugin-aws-1.0.0.jar:?]
>         at org.graylog.aws.s3.S3Reader.readCompressed(S3Reader.java:28) [graylog-plugin-aws-1.0.0.jar:?]
>         at org.graylog.aws.inputs.cloudtrail.CloudTrailSubscriber.run(CloudTrailSubscriber.java:108) [graylog-plugin-aws-1.0.0.jar:?]
> Caused by: java.net.SocketTimeoutException: connect timed out
>         at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_101]
>         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_101]
>         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_101]
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_101]
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_101]
>         at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_101]
>         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337) ~[?:?]
>         at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:132) ~[?:?]
>         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) ~[?:?]
>         ... 23 more
> 2016-09-20T12:54:16.614Z ERROR [CloudTrailSubscriber] Could not read CloudTrail log file for <sapcloudtrail>. Skipping.
> com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connect to sapcloudtrail.s3.amazonaws.com:443 [sapcloudtrail.s3.amazonaws.com/54.231.72.51] failed: connect timed out
>         at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:713) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:453) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:415) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:364) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3964) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1259) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1134) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at org.graylog.aws.s3.S3Reader.readCompressed(S3Reader.java:28) ~[graylog-plugin-aws-1.0.0.jar:?]
>         at org.graylog.aws.inputs.cloudtrail.CloudTrailSubscriber.run(CloudTrailSubscriber.java:108) [graylog-plugin-aws-1.0.0.jar:?]
> Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to sapcloudtrail.s3.amazonaws.com:443 [sapcloudtrail.s3.amazonaws.com/54.231.72.51] failed: connect timed out
>         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150) ~[?:?]
>         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[?:?]
>         at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
>         at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[?:?]
>         at com.amazonaws.http.conn.$Proxy154.connect(Unknown Source) ~[?:?]
>         at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[?:?]
>         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[?:?]
>         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[?:?]
>         at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[?:?]
>         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[?:?]
>         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[?:?]
>         at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:858) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:701) ~[?:?]
>         ... 8 more
> Caused by: java.net.SocketTimeoutException: connect timed out
>         at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_101]
>         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_101]
>         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_101]
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_101]
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_101]
>         at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_101]
>         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337) ~[?:?]
>         at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:132) ~[?:?]
>         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) ~[?:?]
>         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[?:?]
>         at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
>         at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[?:?]
>         at com.amazonaws.http.conn.$Proxy154.connect(Unknown Source) ~[?:?]
>         at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[?:?]
>         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[?:?]
>         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[?:?]
>         at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[?:?]
>         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[?:?]
>         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[?:?]
>         at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:858) ~[?:?]
>         at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:701) ~[?:?]
>         ... 8 more
> 

The proxy is configured propperly:

> root@mo-81185639b:/var/log/graylog-server# curl https://sapcloudtrail.s3.amazonaws.com
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>43F82724745C9EC2</RequestId><HostId>x6duNrRHR6HUwuvkuUn1A0bCte5YYScHJP7g5Dby9/AxbkI8LcZpoiEWYMlFHDuE</HostId></Error>root@mo-81185639b:/var/log/graylog-server#
> root@mo-81185639b:/var/log/graylog-server#

Any Ideas?

**Comment by lennartkoopmann** [comment]
Connection timeouts look like a proxy or AWS issue. Please re-open this issue if the problem still exists and ist reproducible. Thanks!
