### ISSUE TITLE
better example needed for creating permissions.json

### ISSUE THREAD

**Issue by daniejstriata** [Graylog2/graylog-plugin-aws#172]
Hi,

I cannot get past creating a working permissions.json: Is it possible to add an example so I can see what a working config would look like? Mine prints out:

> An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: The policy failed legacy parsing

```

Copy the ARN of the role you just created. You'll need it in the next step.

Create a new file called permissions.json and set both ARNs to the ARNs your copied above:

{
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "kinesis:PutRecord",
      "Resource": "[YOUR KINESIS STREAM ARN HERE]"
    },
    {
      "Effect": "Allow",
      "Action": "iam:PassRole",
      "Resource": "[YOUR IAM ARN HERE]"
    }
  ]
}
```

Mine looks like:

```
{
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "kinesis:PutRecord",
      "Resource": "arn:aws:kinesis:eu-west-2:79...34:stream/EU-flowlogs"
    },
    {
      "Effect": "Allow",
      "Action": "iam:PassRole",
     "Resource": "arn:aws:iam:79...34:user/da...er@st...m"
    }
  ]
}
```

**Comment by danotorrey** [comment]
Hi @daniejstriata,
The example policy document appears to be valid. I was able to use it successfully in a test.

It looks like the error is occurring when the AWS CLI attempts to parse the JSON policy document. The AWS CLI JSON parser is quite strict. Even a blank line at the beginning can cause this error. Could you please double check to make sure there are no extra lines or spaces around the JSON in the document?

If the error continues to occur, could you please upload the full file to this issue (with the `resource` value obfuscated)?
