### ISSUE TITLE
CLoudtrail plugin - unable to configure http proxy

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog-plugin-aws#2]
> It is not possible to provide http proxy conf to Cloudtrail plugin to make AWS API requests pass through.

Source: https://github.com/Graylog2/graylog2-server/issues/996

**Comment by Noah-Hughes** [comment]
It does not appear that the pluin uses the proxy variable that is set in the graylog config.

**Comment by tjdecke** [comment]
This would be really useful, currently facing the same issue. I'd probably want to set the proxy separately from the graylog config.
