### ISSUE TITLE
Support RDS logs through Cloudwatch - Kinesis

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-aws#24]
As described in #23

**Comment by lennartkoopmann** [comment]
@romanr From what I can see, these logs are only including metrics. If that is the case, we are probably not going to implement it. I'd accept a PR though.

**Comment by romanr** [comment]
What is the problem, what is the difference between these and other types of logs? Can the plugin simply pass the logs further so we can parse them with regex? just accept entire message payload as message? Without checking for 15 fields.

**Comment by lennartkoopmann** [comment]
Flowlog messages have a completely different structure and apply special parsing and transformations.

Passing it on as the raw JSON and then parsing that JSON with a pipeline function would work but you'd have to build this yourself. Parsing metrics simply does not fit onto our roadmap.

**Comment by kieulam141** [comment]
Hi @lennartkoopmann 
Can I use "AWS log" Input for this case?
