### ISSUE TITLE
plugins doesn't work for all regions?

### ISSUE THREAD

**Issue by jhaar** [Graylog2/graylog-plugin-aws#3]
Hi there

I've got this plugin up and running in US-WEST-2, and then configured all other regions identically.

However, now I get this error in /var/log/graylog-server/server.log

The bucket you are attempting to access must be addressed using the specified endpoint 
(Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 23esadd323s), S3 Extended Request ID:.....

Googling that implies it's something to do with the S3 bucket not being global? So I tried to create the same S3 bucket in all other regions, but got a "already exists" error - which implies the bucket is actually OK

Any other reason it should act like this? BTW, us-east-1 works fine - so I actually have two working - but the rest do not - although the S3 bucket shows logs from *all* of them (ie it's like an authentication problem - but it's the same account for all of them - and it obviously has access to the S3 bucket otherwise it wouldn't be working for any of them)

Thanks

**Comment by joschi** [comment]
Fixed by closing #6.
