### ISSUE TITLE
Question: How to show field requestParameters and responseElements?

### ISSUE THREAD

**Issue by jim3ma** [Graylog2/graylog-plugin-aws#31]
I'm newbie to graylog.

I use graylog 2.1.2 and graylog-plugin-aws 1.2, while I can not find field requestParameters and responseElements.

I found these field have been parsed in code. 

I do not know how to configure my graylog.

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
