### ISSUE TITLE
AWS cloud-trails and cloud-watch don't work behind proxy

### ISSUE THREAD

**Issue by kitsushadow** [Graylog2/graylog-plugin-aws#32]
We are hosting our graylog server behind a proxy and we believe that it is interfering with the plugins ability to reach out to AWS Services.

@lennartkoopmann This is the Blackstone team

**Comment by lennartkoopmann** [comment]
dc5ccedb079272b23560a5be707fdb5f90f8da5b

**Comment by kitsushadow** [comment]
Awesome, i'll close and we'll give a go tomorrow. If we have questions we can give you guys a call.
