### ISSUE TITLE
Cloudtrail plugin is not working

### ISSUE THREAD

**Issue by leomazzo** [Graylog2/graylog-plugin-aws#34]
Hi, 

I have done the configuration of section "CloudTrail setup and configuration". I have created the policies, the configuration of plugin, etc... but i can see messages of cloudtrail on search menu at Graylog2 Web Interface

I can't see any messages at Graylog2 server.log ...... i have not errors.

<img width="756" alt="captura de tela 2017-04-13 as 13 38 19" src="https://cloud.githubusercontent.com/assets/13120781/25014554/9dbc0490-204e-11e7-816a-ba6ef0fb89f4.png">

I am using Graylog 2.2.3+7adc951 on ip-10-XXX-X-XXX.ec2.internal (Oracle Corporation 1.8.0_121 on Linux 3.10.0-327.10.1.el7.x86_64)

<img width="683" alt="captura de tela 2017-04-13 as 13 40 37" src="https://cloud.githubusercontent.com/assets/13120781/25014586/c9485596-204e-11e7-8979-24738cadbbeb.png">

<img width="998" alt="captura de tela 2017-04-13 as 13 41 49" src="https://cloud.githubusercontent.com/assets/13120781/25014646/fe54807a-204e-11e7-8301-7acfa9f1e65f.png">

I would like to know how to enable any debug log ....

Regards.,

**Comment by arunamat** [comment]
@leomazzo, is your issue resolved? I'm facing a similar issue with the latest version.

**Comment by danotorrey** [comment]
@leomazzo @arunamat Is this issue still occurring? Could you please enable Debug logging level (in System > Logging > Subsystem: Graylog) and try again to reproduce the issue? The Debug logs might provide additional troubleshooting details.

**Comment by danotorrey** [comment]
@leomazzo @arunamat Can you please verify that the SQS subscription is not set for "Raw message delivery"? This option will prevent the CloudTrail input from working.

See this AWS docs page for more info. https://docs.aws.amazon.com/sns/latest/dg/sns-large-payload-raw-message-delivery.html

Please let us know if this does not fix it. We are happy to investigate further if needed.
