### ISSUE TITLE
How to connect kinesis when using SSL

### ISSUE THREAD

**Issue by estein9825** [Graylog2/graylog-plugin-aws#365]
I attempted to connect to kinesis and I get the notification:

```
Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

HTTPS works in general for my application when communicating with MongoDB and the like. Is there some other cert I need to import for kinesis to work?

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
