### ISSUE TITLE
Role Based Authentication

### ISSUE THREAD

**Issue by ricey99** [Graylog2/graylog-plugin-aws#48]
Would it be possible to include role and cross account role access rather than just access/secret keys.

This would be very beneficial when running Graylog in AWS.

**Comment by radykal-com** [comment]
Hello,
Could you explain us a bit more about what do you expect? It can work with Instance profile authentication right now. How is that cross account role setup? Any example?

**Comment by ricey99** [comment]
Hi

I am taking my experience from the Splunk Add on for AWS....

As you have stated it looks like your plugin allows it is assume a role via the instance profile, the ability to add additional roles to the plugin from the same AWS account would allow use to setup roles in other AWS accounts with cross account access which would enable access to the account without having to manage access keys and secrets.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

http://docs.splunk.com/Documentation/AddOns/latest/AWS/ConfigureAWSpermissions

https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html

Hope that helps.

Thanks

**Comment by radykal-com** [comment]
Ok, what I see is that a new config field is required to set the ARN of the assumed role to access the required resources, is this correct?

**Comment by ricey99** [comment]
Yes, that sounds correct, if this could be set at the input level it would allow for inputs from multiple accounts.

Thanks

**Comment by radykal-com** [comment]
Sure, to check the permissions to assume the role it should follow the current chain of authentication right? I mean, if the input has KEY+SECRET it should try to assume the role using them, if not, try it with the instance profile.

If this is correct, I can help with the implementation as soon some maintaineer appears by here to agree with this

**Comment by ricey99** [comment]
Yes, that is correct, Thanks !!

**Comment by joschi** [comment]
@radykal-com Sure, go for it! We'll happily review any pull request you're contributing!

**Comment by radykal-com** [comment]
#49 is ready. I have tested it in my AWS environment

**Comment by bernd** [comment]
#49 hast been merged and will be in the upcoming 2.4 release. Thank you @radykal-com!

**Comment by radykal-com** [comment]
👍
