### ISSUE TITLE
Downloaded the latest AWS plugin will not load

### ISSUE THREAD

**Issue by alias454** [Graylog2/graylog-plugin-aws#50]
I see this error after download the jar file and restarting my GL instance.
2017-10-20T19:55:59.801Z ERROR [CmdLineTool] Plugin "AWS plugins" requires version 2.4.0-beta.1 - not loading!

Version: 2.3.2+3df951e, codename Tegernseer
JVM: PID 47140, Oracle Corporation 1.8.0_141 on Linux 3.13.0-105-generic

**Comment by radykal-com** [comment]
The version of the plugin you installed is compatible with Graylog 2.4.x versions and you are running Graylog 2.3.2, so only versions 2.3.x of the AWS Plugin are compatible with it

**Comment by alias454** [comment]
Oh that would do it. Thanks
