### ISSUE TITLE
aws logs stream can't connect to kinesis due to table name issue

### ISSUE THREAD

**Issue by SeerKan** [Graylog2/graylog-plugin-aws#51]
errors:

> 2017-10-26 11:36:09,575 ERROR: com.amazonaws.services.kinesis.leases.impl.LeaseManager - Failed to get table status for graylog-aws-plugin-arn:aws:kinesis:eu-west-1:534996215098:stream/stage_ecs
> com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: 1 validation error detected: Value 'graylog-aws-plugin-arn:aws:kinesis:eu-west-1:534996215098:stream/stage_ecs' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+ (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: O38921VR7HBC99LRCI561THGJRVV4KQNSO5AEMVJF66Q9ASUAAJG)

using graylog 4 beta1 with the plugin preinstalled and the aws user has the recommended permissions to cloudwatch, dynamodb and kinesis streams.

**Comment by SeerKan** [comment]
Also, If I try to update settings from the configuration part I get the error bellow (tried even without any inputs )

Could not update search config: org.graylog.aws.config.AWSPluginConfiguration
Search config update failed: Error: cannot PUT https://graylog-stage.domain.com/api/system/cluster_config/org.graylog.aws.config.AWSPluginConfiguration (400)

**Comment by joschi** [comment]
> Value 'graylog-aws-plugin-arn:aws:kinesis:eu-west-1:534996215098:stream/stage_ecs' at 'tableName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+

You're using an invalid character in the "tableName" attribute (the colon ':' to be exact).

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by sensware** [comment]
Could not update search config: org.graylog.aws.config.AWSPluginConfiguration
Search config update failed: Error: cannot PUT https://graylog-stage.domain.com/api/system/cluster_config/org.graylog.aws.config.AWSPluginConfiguration (400)
[https://imgur.com/mFKfe2k](https://imgur.com/mFKfe2k)

I am getting the same error while trying to update AWS configuration  with my AWS AK/SK 
I tried with or without the keys. Using the latest AMI on AWS on an m4.large instance

All other dialogs on Configurations page work fine
Please advise
