### ISSUE TITLE
Can't receive messages from SQS 

### ISSUE THREAD

**Issue by ColeBracew** [Graylog2/graylog-plugin-aws#56]
I have tried creating a AWS CloudTrail input and i know all the variables within are correct.

This is the out put in my Graylog log file:

2017-12-06T15:57:32.846Z ERROR [CloudTrailSubscriber] Could not read messages from SQS. This is most likely a misconfiguration of the plugin. Going into sleep loop and retrying.
com.amazonaws.services.sqs.model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version. (Service: AmazonSQS; Status Code: 400; Error Code: AWS.SimpleQueueService.NonExistentQueue; Request ID: b596-50e5-b285-f11b09ea677c)

I googled the message and i'm sure the region is correct, i have also tried the SQS URL and have still had no joy. 

Can anyone help? 

Graylog version: Graylog v2.4.0-beta.2
Plugin Version: graylog-plugin-aws-2.4.0-beta.1.jar

**Comment by bernd** [comment]
`com.amazonaws.services.sqs.model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version.`

@ColeBracew This looks like your queue does not exist. Please check your config again.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
