### ISSUE TITLE
Allow use of IAM role for access control rather than key

### ISSUE THREAD

**Issue by petestorey26** [Graylog2/graylog-plugin-aws#57]
Since it's easy to configure the graylog server instance to have an IAM role which can provide access, it would be god if we can leave the keys blank and simply allow it to use the role instead - an easy fix I'd imagine?

**Comment by radykal-com** [comment]
Hello @petestorey26
This functionality is already implemented. If you don't specify the keys in the input config, it will try to authenticate using the roles assigned to the instance profile.

**Comment by jalogisch** [comment]
@petestorey26 what @radykal-com wrote - if you have further issues please open a new issue or reopen the current one.
