### ISSUE TITLE
Add documentation for configuring the graylog-plugin-aws inside the graylog.conf

### ISSUE THREAD

**Issue by daytonpa** [Graylog2/graylog-plugin-aws#62]
I cannot find any resources, or if they exist, there isn't an easy way to find those resources.  It would be nice to have documented settings/flags for the `server.conf` file for configuring this plugin.

**Comment by joschi** [comment]
@daytonpa This plugin doesn't have any configuration settings in the Graylog configuration file.

It's configured via the System/Configurations page in the Graylog web interface.

**Comment by daytonpa** [comment]
From an automation standpoint, could this be added as a feature?

**Comment by joschi** [comment]
@daytonpa No, but you could use the Graylog REST API to change the configuration of the AWS plugin in a running instance.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
