### ISSUE TITLE
More documentation about IAM setup

### ISSUE THREAD

**Issue by evansj** [Graylog2/graylog-plugin-aws#64]
Background: I am trying to set things up so that my CloudWatch Logs are pushed through to a Graylog instance. My Graylog is running in a Docker container, and all of the AWS infrastructure is created and configured using Terraform scripts.

In the Graylog UI, the AWS Plugin Configuration popup says the following regarding the AWS access key and secret key fields:

> Please consult the documentation for suggested rights to assign to the underlying IAM user.

The only documentation I can find is [the README](/Graylog2/graylog-plugin-aws/blob/master/README.md).

This contains a section about permissions required for AWS entity translation, so in my Terraform configs I've created a new user and attached this policy.

The documentation then goes on to explain the requirements for Flowlogs, then CloudTrail. The CloudTrail part will definitely be of interest but my immediate aim is to get access to CloudWatch Logs, and there isn't a specific section about that in the document.

The UI for the "AWS Logs" input has similar references to the README.

> Access key of an AWS user with sufficient permissions. (See documentation)

> The name of the Kinesis stream that receives your messages. See README for instructions on how to connect messages to a Kinesis Stream.

Is there any documentation which covers the specific requirements for the AWS Logs input?

Thanks in advance.

**Comment by danotorrey** [comment]
Hi @evansj,
We have improved our README file and documented the specific permissions needed for the AWS Logs/Flow logs inputs here https://github.com/Graylog2/graylog-plugin-aws#step-3-create-aws-user-for-running-the-input.

Please let us know if you have any more questions.
