### ISSUE TITLE
Cloudtrail plugin is not reading messages from SQS

### ISSUE THREAD

**Issue by arunamat** [Graylog2/graylog-plugin-aws#65]
Hi,

I have done the necessary configurations for cloudtrail notifications. I can see messages being delivered in my SQS but for some reason graylog is not reading those messages. I checked the server logs too. There isn't any errors being thrown. Is there any way to enable debug for the plugin? I'm using the latest graylog version 2.4.3.

Thanks in advance.

**Comment by hhh0505** [comment]
same here, anything for this?

**Comment by arunamat** [comment]
issue has been resolved. had to configure cloudtrail to directly post events to the sns topic.
