### ISSUE TITLE
Multiple AWS Flog Logs Input not working any more

### ISSUE THREAD

**Issue by jonmelia** [Graylog2/graylog-plugin-aws#67]
Up until recently, mid Feb, we used to be able to run 2 AWS Flow Logs Inputs from 2 separate Kinesis streams and messages would come into both simultaneously.  Now it seems that only one Input will accept logs at any one time.  Both of them work, but only individually.  They both won't collect messages from the separate streams at the same time.  The Kinesis streams are fine, but Graylog is only pulling info from one Input even if they are both started. 
Attempted
1.) Deleted and recreated Inputs
2.) Installed the latest plugin beta
Graylog v 2.3 in use

**Comment by lennartkoopmann** [comment]
Can you please send your `graylog-server` logs? It would be great to see logs of the input being stopped and started.

**Comment by jonmelia** [comment]
Just noticed that when I thought i had updated to the latest plugin it is still trying to use the old plugin which I had renamed.  I have now removed the old plugin and added the 2.4.0-beta.1 plugin into the plugins directory and restarted graylog-server, but it is not picking up the new plugin...  Message 
Plugin "AWS Plugins" requires version 2.4.0-beta.1 - not loading

**Comment by lennartkoopmann** [comment]
@jonmelia Graylog 2.4 ships with the AWS plugins by default. You should not have to install it manually. What Graylog version are you running?

**Comment by jonmelia** [comment]
v 2.3

**Comment by lennartkoopmann** [comment]
You'll need the v2.3 version of the AWS plugins for this to work. I'd recommending upgrading to Graylog v2.4 instead because this will bring you the AWS plugins out of the box. Please re-open this ticket if the issue persists.
