### ISSUE TITLE
Missing region EU-WEST-3 (Paris)

### ISSUE THREAD

**Issue by Guido0370** [Graylog2/graylog-plugin-aws#73]
AWS has new region eu-west-3 and graylog knows nothing about it.

**Comment by radykal-com** [comment]
I think this issue and also #71 would be fixed if the version of the AWS SDK is updated to latest version:
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java
