### ISSUE TITLE
Add a generic kinesis plugin

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog-plugin-aws#82]
I have a lot of different message types (cloudtrail, flowlogs, instance logs, elb logs, lambda) sent to aws kinesis. It would be great if Graylog could subscribe to this kinesis stream and read the messages (string or json).

This plugin is too specific (AWS FlowLogs input) for my custom solution. My logs are coming from multiple source account and already contain meta information like aws account id, aws region and so on.

**Comment by runningman84** [comment]
@lennartkoopmann what do you think?

**Comment by jalogisch** [comment]
currently this will be not on the roadmap - that is why i'll close this now.
